# Spaceship theme config
SPACESHIP_PROMPT_ADD_NEWLINE="true"
#SPACESHIP_CHAR_PREFIX="\ue267"
SPACESHIP_CHAR_SYMBOL="\uf135"
SPACESHIP_CHAR_SUFFIX="  "
#SPACESHIP_CHAR_COLOR_SUCCESS="yellow"
#SPACESHIP_PROMPT_DEFAULT_PREFIX="$USER"
#SPACESHIP_PROMPT_FIRST_PREFIX_SHOW="true"
SPACESHIP_USER_SHOW="needed"
