# Spaceship theme config

SPACESHIP_PROMPT_ADD_NEWLINE=true
# SPACESHIP_PROMPT_DEFAULT_PREFIX="$USER"
# SPACESHIP_PROMP_FIRST_PREFIX_SHOW="true"

# Cohete
# SPACESHIP_CHAR_SYMBOL="\uf135 "
# Console Line
# SPACESHIP_CHAR_SYMBOL="\ufcb5 "
# Lambda
# SPACESHIP_CHAR_SYMBOL="\ufb26 "
# Oct Code
# SPACESHIP_CHAR_SYMBOL="\uf44f "
# FA Code
# SPACESHIP_CHAR_SYMBOL="\uf121 "
# FA Chevron Right
SPACESHIP_CHAR_SYMBOL="\uf054"
SPACESHIP_CHAR_SUFFIX=" "

SPACESHIP_TIME_SHOW=true

SPACESHIP_USER_SHOW=needed

SPACESHIP_BATTERY_SHOW=false