#!/usr/bin/env bash

set -euo pipefail

source "$DOTLY_PATH/scripts/core/_main.sh"

##? Install a package
#?? 1.0.0
##?
##? Usage:
##?    brew_install

docs::parse "$@"

if [[ $# -gt 0 ]]; then
  package=$(brew search | grep "$1" | fzf)
else
  package=$(brew search | fzf)
fi

if [[ -z ${package} ]]; then
  echo "You haven't selected any package to install! ༼つ◕_◕༽つ"

  exit 1
fi

brew install "${package}"
