#!/usr/bin/env bash

set -euo pipefail

source "$DOTLY_PATH/scripts/core/_main.sh"

##? Uninstall brew package --cask
#?? 1.0.0
##?
##? Usage:
##?    brew_cask_uninstall

docs::parse "$@"

if [[ $# -gt 0 ]]; then
  to_uninstall=$(brew list --cask | grep $1 | fzf)
else
  to_uninstall=$(brew list --cask | fzf)
fi

if [[ -z ${to_uninstall} ]]; then
  echo "You haven't selected any package to uninstall! ༼つ◕_◕༽つ"

  exit 1
fi

brew uninstall ${to_uninstall} --cask
