#!/usr/bin/env bash

set -euo pipefail

source "$DOTLY_PATH/scripts/core/_main.sh"

##? Uninstall a paclage
#?? 1.0.0
##?
##? Usage:
##?    brew_uninstall

docs::parse "$@"

if [[ $# -gt 0 ]]; then
  to_uninstall=$(brew leaves | grep "$1" | fzf)
else
  to_uninstall=$(brew leaves | fzf)
fi

if [[ -z ${to_uninstall} ]]; then
  echo "You haven't selected any package to uninstall! ༼つ◕_◕༽つ"

  exit 1
fi

brew uninstall "${to_uninstall}"
