#!/usr/bin/env bash

set -euo pipefail

source "$DOTLY_PATH/scripts/core/_main.sh"

##? Install brew package --cask
#?? 1.0.0
##?
##? Usage:
##?    install_cask

docs::parse "$@"

if [[ $# -gt 0 ]]; then
  package=$(brew search --cask | grep $1 | fzf)
else
  package=$(brew search --cask | fzf)
fi

if [[ -z ${package} ]]; then
  echo "You haven't selected any package to install! ༼つ◕_◕༽つ"

  exit 1
fi

brew install ${package} --cask
