#!/usr/bin/env bash

set -euo pipefail

source "$DOTLY_PATH/scripts/core/_main.sh"

##? Sync all installed packages (previously exported)
#?? 1.0.0
##?
##? Usage:
##?    export

docs::parse "$@"

brew services stop --all
brew bundle --file="$HOMEBREW_BUNDLE_FILE_PATH" --force
echo 'Brew apps imported!'

ln -s "$(brew --prefix)/bin/gsha256sum" "$(brew --prefix)/bin/sha256sum"

pip3 install -r "$DOTFILES_PATH/langs/python/requirements.txt"
echo 'Python apps imported!'

xargs -I_ npm install -g "_" <"$DOTFILES_PATH/langs/js/global_modules.txt"
echo 'NPM apps imported!'

dot package export
